# Approach to Part C

In 431, my primary goal is to immerse you in several cases, which will demonstrate good statistical practice in the analysis of data using multiple regression models. Often, we will leave gaps for 432, but the principal goal is to get you to the point where you can do a solid (if not quite complete) analysis of data in Study 2 for your project.

The ten main topics to be discussed or reviewed in these notes are:

1.	Describing the multivariate relationship
    a.	Scatterplots and smoothing
    b.	Correlation coefficients, Correlation matrices
2.	Transformations and Re-expression
    a.	The need for transformation
    b.	Using a Box-Cox method to help identify effective transformation choices
3.	Testing the significance of a multiple regression model
    a.	T tests for individual predictors as last predictor in
    b.	Global F tests based on ANOVA to assess overall predictive significance
    c.	Incremental and Sequential testing of groups of predictors
4.	Interpreting the predictive value of a model
    a.	R^2^ and Adjusted R^2^, along with AIC and BIC 
    b.	Residual standard deviation and RMSE
    c.	Estimating the effect size in terms of raw units, standard deviations or IQRs
    d.	Fitted values; Distinguishing prediction from confidence intervals
5.	Checking model assumptions
    a.	Residual Analysis including studentized residuals, and the major plots
    b.	Identifying points with high Leverage
    c.	Assessing Influence numerically and graphically
    d.	Measuring and addressing collinearity
6.	Model Selection
    a.	The importance of parsimony
    b.	Stepwise regression and other automated techniques
7.	Assessing Predictive Accuracy through Cross-Validation
    a.	Summaries of predictive error
8.	Dealing with Missing Values sensibly
    a.	Imputation vs. Complete Case analyses
    b.	Including a missing data category vs. simple imputation vs. removal
9.	Dealing with Categorical Predictors
    a.	Indicator variables
    b.	Impact of Categorical Variables on the rest of our Modeling 
10.	Summarizing the Key Findings of the Model, briefly and accurately
    a.	Making the distinction between causal findings and associations
    b.	The importance of logic, theory and empirical evidence. (LTE)

## Additional Reading 

The Vittinghoff textbook is strong in this area. The relevant sections of the text for 431 Part C are

- Section 3.3 on the Simple Linear Regression Model
- Chapter 4 on Linear Regression, where most of the material is relevant to 431, although we'll postpone the discussion of cubic splines, mostly, to 432.
- Chapters 10 (Model Selection) in particular the alternatives to R^2^ in 10.1.3.2 and some of the material on cross-validation, though we'll do much more in 432.
- A little of Chapter 11 (Missing Data), specifically, section 11.1.1 and a little of section 11.3, although we'll do more on this in 432 as well.



